// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("CompiledTrigger")>]
[<assembly: AssemblyProductAttribute("TibruFunctions")>]
[<assembly: AssemblyDescriptionAttribute("Azure functions for Tibru contacts system")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "CompiledTrigger"
    let [<Literal>] AssemblyProduct = "TibruFunctions"
    let [<Literal>] AssemblyDescription = "Azure functions for Tibru contacts system"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
